# SwiftLint Configuration File
# https://github.com/realm/SwiftLint

# Paths to include during linting. `--path` is ignored if present.
included:
  - IOS Sort

# Paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods
  - IOS Sort.xcodeproj
  - IOS SortTests
  - IOS SortUITests

# Rules to disable
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - identifier_name
  - todo

# Rules to enable
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - strong_iboutlet
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Analyzer rules to enable
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Custom rule configurations
custom_rules:
  # Custom rule for TODO comments
  todo_comment:
    name: "TODO Comment"
    regex: 'TODO|FIXME|HACK|NOTE'
    message: "TODO comments should be resolved before committing"
    severity: warning

# File header configuration
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  .*
                    \/\/
                    \/\/  Created by .* on .*\.
                    \/\/

# Line length configuration
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 400

# File length
file_length:
  warning: 500
  error: 1000

# Identifier name rules
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - urlRequest
    - urlResponse

# Force unwrapping
force_unwrapping:
  severity: warning

# Implicitly unwrapped optional
implicitly_unwrapped_optional:
  severity: warning

# Empty count
empty_count:
  severity: warning

# Empty string
empty_string:
  severity: warning

# Legacy random
legacy_random:
  severity: warning

# Operator usage whitespace
operator_usage_whitespace:
  severity: warning

# Redundant nil coalescing
redundant_nil_coalescing:
  severity: warning

# Redundant type annotation
redundant_type_annotation:
  severity: warning

# Strong IBOutlet
strong_iboutlet:
  severity: warning

# Switch case on newline
switch_case_on_newline:
  severity: warning

# Unneeded parentheses in closure argument
unneeded_parentheses_in_closure_argument:
  severity: warning

# Vertical parameter alignment on call
vertical_parameter_alignment_on_call:
  severity: warning

# Vertical whitespace closing braces
vertical_whitespace_closing_braces:
  severity: warning

# Vertical whitespace opening braces
vertical_whitespace_opening_braces:
  severity: warning

# Yoda condition
yoda_condition:
  severity: warning
